---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nettest

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nettest
rules:
  - apiGroups: [""]
    resources:
      - services
      - pods
      - configmaps
      - secrets
    verbs:
      - get
      - list
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nettest
subjects:
  - kind: ServiceAccount
    name: nettest
roleRef:
  kind: Role
  name: nettest
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: nettest
spec:
  serviceAccountName: nettest
  containers:
    - name: nettest
      image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_nettest:1.0.2
